In [16]:
# https://github.com/facebookresearch/faiss/wiki/Getting-started
# https://pypi.org/project/faiss-cpu/
import faiss
import json
import numpy as np

In [8]:
# embeddings
embeddings = np.load("../data/embeddings/embeddings.npy")
dim = embeddings.shape[1]

xb = embeddings[:30000].astype("float32")
xq = embeddings[30000:30100].astype("float32")

In [9]:
# build the index
index = faiss.IndexFlatL2(dim)   
print(index.is_trained)

# add vectors to the index
index.add(xb)                  
print(index.ntotal)

True
30000


In [15]:
k=3
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[16796 24712 20958]
 [18555 20709 21874]
 [18073 29656 28148]
 [20721 20713 27767]
 [20721 14817 18555]]
[[28736 22276 19298]
 [18289 21414 19192]
 [15084 18883 24233]
 [22764 22767 22771]
 [20992 20506 14580]]


In [17]:
with open("../data/embeddings/id_embeddings.json") as fp:
    id_embeddings = json.load(fp)
    id_embeddings = {int(k): v for k,v in id_embeddings.items()}

In [19]:
id_embeddings[16796], id_embeddings[30000]

('GC00000281_r1_1', 'GC00005403_2')